export const SOCKET = {
    URL: '127.0.0.1:3000',
    EMIT_EVENTS: {
        GET_ROOM_INFORMATIONS: "GET_ROOM_INFORMATIONS",
        CREATE_NICKNAME: "CREATE_NICKNAME",
        CREATE_ROOM: "CREATE_ROOM",
        JOIN_ROOM: "JOIN_ROOM",
        SERVER_PLAYER_READY: "SERVER_PLAYER_READY",
        SERVER_COMPLETE_WORD: "SERVER_COMPLETE_WORD",
        SERVER_USER_INFORMATION: "SERVER_USER_INFORMATION"
    },
    ON_EVENTS: {
        CONNECT: "connect",
        CLIENT_ROOM_INFORMATIONS: "CLIENT_ROOM_INFORMATIONS",
        CREATE_NICKNAME: "CREATE_NICKNAME",
        CREATE_ROOM: "CREATE_ROOM",
        JOIN_ROOM: "JOIN_ROOM",
        SPECIAL_ROOM_INFORMATION: "SPECIAL_ROOM_INFORMATION",
        CLIENT_GAME_INFORMATIONS: "CLIENT_GAME_INFORMATIONS",
        CLIENT_COMPLETE_WORD: "CLIENT_COMPLETE_WORD",
        CLIENT_END_GAME: "CLIENT_END_GAME",
    },

}
