export const GAME_MODE = {
    CLASSIC: 1,
    LANGUAGE: 2
}

export const PORT = 3000;

export const EMIT_EVENTS = {
    CLIENT_ROOM_INFORMATIONS: "CLIENT_ROOM_INFORMATIONS",
    CREATE_NICKNAME: "CREATE_NICKNAME",
    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
};

export const ON_EVENTS = {
    GET_ROOM_INFORMATIONS: "GET_ROOM_INFORMATIONS",
    CREATE_NICKNAME: "CREATE_NICKNAME",
    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
};
